global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j-exporter:9099']
  
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']